package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseOutlineFileLanguages(t *testing.T) {
	tests := []struct {
		path      string
		source    string
		wantName  string
		wantKind  string
		wantCall  string
		wantOther string
	}{
		{"main.go", `package p
type Config struct { Timeout int }
func Run(v int) error { return helper(v) }
func helper(v int) error { return nil }
`, "Run", "fn", "helper", "Config"},
		{"src/lib.rs", `struct Config { timeout: u64 }
fn run(v: i32) -> bool { helper(v) }
fn helper(v: i32) -> bool { true }
`, "run", "fn", "helper", "Config"},
		{"app.py", `class Config:
    timeout: int
def run(value: int) -> bool:
    return helper(value)
def helper(value: int) -> bool:
    return True
`, "run", "fn", "helper", "Config"},
		{"app.ts", `interface Config { timeout: number }
export function run(value: number): boolean { return helper(value) }
const helper = (value: number): boolean => true
`, "run", "fn", "helper", "Config"},
		{"app.js", `class Config { constructor(timeout) { this.timeout = timeout } }
function run(value) { return helper(value) }
const helper = (value) => true
`, "run", "fn", "helper", "Config"},
		{"src/main/java/App.java", `class App {
  boolean run(int value) { return helper(value); }
  boolean helper(int value) { return true; }
}
`, "run", "method", "helper", "App"},
	}
	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			symbols, skipped, err := parseOutlineFile(tt.path, []byte(tt.source))
			if err != nil || skipped != "" {
				t.Fatalf("parse: skipped=%q err=%v", skipped, err)
			}
			got := rawSymbolNamed(symbols, tt.wantName)
			if got == nil {
				t.Fatalf("%s missing in %+v", tt.wantName, symbols)
			}
			if got.Kind != tt.wantKind {
				t.Errorf("%s kind = %q, want %q", tt.wantName, got.Kind, tt.wantKind)
			}
			if !containsString(got.Calls, tt.wantCall) {
				t.Errorf("%s calls = %v, want %s", tt.wantName, got.Calls, tt.wantCall)
			}
			if rawSymbolNamed(symbols, tt.wantOther) == nil {
				t.Errorf("%s missing in %+v", tt.wantOther, symbols)
			}
		})
	}
}

func TestParseOutlineFileGeneratedAndUnsupported(t *testing.T) {
	if symbols, skipped, err := parseOutlineFile("generated.go", []byte("// Code generated by tool. DO NOT EDIT.\npackage p\n")); err != nil || symbols != nil || skipped != "generated" {
		t.Fatalf("generated = symbols:%v skipped:%q err:%v", symbols, skipped, err)
	}
	if _, skipped, err := parseOutlineFile("README.md", []byte("hello")); err != nil || skipped != "unsupported language" {
		t.Fatalf("unsupported = skipped:%q err:%v", skipped, err)
	}
}

func TestDirectlyTouchedSymbolsUsesSmallestEnclosingSymbol(t *testing.T) {
	source := []byte(`class App {
  boolean run(int value) {
    return helper(value);
  }
  boolean helper(int value) { return true; }
}`)
	symbols, _, err := parseOutlineFile("App.java", source)
	if err != nil {
		t.Fatal(err)
	}
	touched := directlyTouchedSymbols(symbols, map[int]bool{3: true})
	if len(touched) != 1 {
		t.Fatalf("touched = %v, want one method", touched)
	}
	for i := range touched {
		if symbols[i].Name != "run" {
			t.Fatalf("touched %s, want run", symbols[i].Name)
		}
	}
}

func TestAnalyzeOutlineUsesCommitSnapshots(t *testing.T) {
	dir := t.TempDir()
	gitTest(t, dir, "init", "-q")
	gitTest(t, dir, "config", "user.email", "test@example.com")
	gitTest(t, dir, "config", "user.name", "Test")
	writeTestFile(t, dir, "main.go", `package p
func helper(v int) int { return v }
func Run(v int) int { return helper(v) }
func Main() int { return Run(1) }
`)
	gitTest(t, dir, "add", "main.go")
	gitTest(t, dir, "commit", "-qm", "base")
	base := strings.TrimSpace(gitTest(t, dir, "rev-parse", "HEAD"))

	writeTestFile(t, dir, "main.go", `package p
func helper(v int) int { return v }
func Run(v int, offset int) int { return helper(v) + offset }
func Main() int { return Run(1, 0) }
`)
	gitTest(t, dir, "add", "main.go")
	gitTest(t, dir, "commit", "-qm", "head")
	head := strings.TrimSpace(gitTest(t, dir, "rev-parse", "HEAD"))
	diffText := gitTest(t, dir, "diff", base, head, "--")

	// Dirty content must not leak into a commit-based analysis.
	writeTestFile(t, dir, "main.go", "package broken\n")
	result, err := analyzeOutline(dir, head, base, ParseUnifiedDiff(diffText))
	if err != nil {
		t.Fatal(err)
	}
	run := resultSymbolNamed(result, "Run")
	if run == nil {
		t.Fatalf("Run missing from %+v", result.Files)
	}
	if run.Change != outlineSignatureChanged {
		t.Errorf("Run change = %s", run.Change)
	}
	if run.FanIn != 1 || len(run.Callers) != 1 || run.Callers[0].Name != "Main" {
		t.Errorf("Run callers/fan-in = %d %+v", run.FanIn, run.Callers)
	}
	if len(run.Callees) != 1 || run.Callees[0].Name != "helper" {
		t.Errorf("Run callees = %+v", run.Callees)
	}
}

func TestClassifyOutlineDeletionOnlyBodyChange(t *testing.T) {
	oldSource := []byte("package p\nfunc Run() int {\n\tx := 1\n\treturn x\n}\n")
	newSource := []byte("package p\nfunc Run() int {\n\treturn 1\n}\n")
	oldSymbols, _, err := parseOutlineFile("main.go", oldSource)
	if err != nil {
		t.Fatal(err)
	}
	newSymbols, _, err := parseOutlineFile("main.go", newSource)
	if err != nil {
		t.Fatal(err)
	}
	diff := &FileDiff{OldPath: "main.go", NewPath: "main.go", Hunks: []Hunk{{Lines: []DiffLine{
		{Kind: LineDel, OldNo: 3, Text: "x := 1"},
	}}}}
	file, _ := classifyOutlineFile(diff,
		map[string][]byte{"main.go": newSource}, map[string][]byte{"main.go": oldSource},
		map[string][]rawOutlineSymbol{"main.go": newSymbols}, map[string][]rawOutlineSymbol{"main.go": oldSymbols})
	if len(file.Symbols) != 1 || file.Symbols[0].Name != "Run" || file.Symbols[0].Change != outlineBodyOnly {
		t.Fatalf("deletion-only classification = %+v", file.Symbols)
	}
}

func TestAnalyzeOutlineRemovedSymbolKeepsSourceCallers(t *testing.T) {
	dir := t.TempDir()
	gitTest(t, dir, "init", "-q")
	gitTest(t, dir, "config", "user.email", "test@example.com")
	gitTest(t, dir, "config", "user.name", "Test")
	writeTestFile(t, dir, "main.go", `package p
func Gone() {}
func Caller() { Gone() }
`)
	gitTest(t, dir, "add", "main.go")
	gitTest(t, dir, "commit", "-qm", "base")
	base := strings.TrimSpace(gitTest(t, dir, "rev-parse", "HEAD"))

	writeTestFile(t, dir, "main.go", `package p
func Caller() { Gone() }
`)
	gitTest(t, dir, "add", "main.go")
	gitTest(t, dir, "commit", "-qm", "head")
	head := strings.TrimSpace(gitTest(t, dir, "rev-parse", "HEAD"))
	diffText := gitTest(t, dir, "diff", base, head, "--")

	result, err := analyzeOutline(dir, head, base, ParseUnifiedDiff(diffText))
	if err != nil {
		t.Fatal(err)
	}
	gone := resultSymbolNamed(result, "Gone")
	if gone == nil || gone.Change != outlineRemoved {
		t.Fatalf("removed symbol = %+v", gone)
	}
	if gone.FanIn != 1 || len(gone.Callers) != 1 || gone.Callers[0].Name != "Caller" {
		t.Fatalf("removed symbol callers = fan-in:%d callers:%+v", gone.FanIn, gone.Callers)
	}
}

func rawSymbolNamed(symbols []rawOutlineSymbol, name string) *rawOutlineSymbol {
	for i := range symbols {
		if symbols[i].Name == name {
			return &symbols[i]
		}
	}
	return nil
}

func resultSymbolNamed(result *outlineResult, name string) *outlineSymbol {
	for fi := range result.Files {
		for si := range result.Files[fi].Symbols {
			if result.Files[fi].Symbols[si].Name == name {
				return &result.Files[fi].Symbols[si]
			}
		}
	}
	return nil
}

func containsString(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}

func gitTest(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, out)
	}
	return string(out)
}

func writeTestFile(t *testing.T, dir, name, content string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
